<?php

namespace AppBundle\Repository;

/**
 * AnimePlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimePlaylistRepository extends \Doctrine\ORM\EntityRepository
{
}
