<?php

namespace AppBundle\Repository;

/**
 * animeAuthorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class animeAuthorsRepository extends \Doctrine\ORM\EntityRepository
{
}
